services:
  spark-master:
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080' # Spark Web UI
      - '7077:7077' # Spark Master Port
      - '4000:4040' # Spark History Server
    networks:
      - spark-net
    volumes:
      - ./graphx-scripts:/opt/graphx-scripts

  spark-worker-1:
    image: bitnami/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - '8081:8081' # Spark Worker UI
    networks:
      - spark-net
    volumes:
      - ./graphx-scripts:/opt/graphx-scripts

  spark-worker-2:
    image: bitnami/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - '8082:8081' # Second worker with a different port mapping
    networks:
      - spark-net
    volumes:
      - ./graphx-scripts:/opt/graphx-scripts

  sbt-builder:
    image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6
    volumes:
      - ./graphx-scripts:/opt/graphx-scripts
    working_dir: /opt/graphx-scripts
    command: sbt package

networks:
  spark-net:
    driver: bridge
